session2/demo3/config/routes.rb
Demo3::Application.routes.draw do
  resources :myclasses

  get "say/hello"

  get "say/goodbye"

end

session2/demo3/app/models/myclass.rb
class Myclass < ActiveRecord::Base
end

session2/demo3/app/controllers/myclasses_controller.rb
class MyclassesController < ApplicationController
  # GET /myclasses
  # GET /myclasses.json
  def index
    @myclasses = Myclass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @myclasses }
    end
  end

  # GET /myclasses/1
  # GET /myclasses/1.json
  def show
    @myclass = Myclass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @myclass }
    end
  end

  # GET /myclasses/new
  # GET /myclasses/new.json
  def new
    @myclass = Myclass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @myclass }
    end
  end

  # GET /myclasses/1/edit
  def edit
    @myclass = Myclass.find(params[:id])
  end

  # POST /myclasses
  # POST /myclasses.json
  def create
    @myclass = Myclass.new(params[:myclass])

    respond_to do |format|
      if @myclass.save
        format.html { redirect_to @myclass, notice: 'Myclass was successfully created.' }
        format.json { render json: @myclass, status: :created, location: @myclass }
      else
        format.html { render action: "new" }
        format.json { render json: @myclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /myclasses/1
  # PUT /myclasses/1.json
  def update
    @myclass = Myclass.find(params[:id])

    respond_to do |format|
      if @myclass.update_attributes(params[:myclass])
        format.html { redirect_to @myclass, notice: 'Myclass was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @myclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myclasses/1
  # DELETE /myclasses/1.json
  def destroy
    @myclass = Myclass.find(params[:id])
    @myclass.destroy

    respond_to do |format|
      format.html { redirect_to myclasses_url }
      format.json { head :no_content }
    end
  end
end

session2/demo3/app/controllers/say_controller.rb
class SayController < ApplicationController
  require 'functions'
  def hello
    
    @myvar =  Myclass.find(2).name
  end

  def goodbye
  end
end

session2/demo3/app/helpers/myclasses_helper.rb
module MyclassesHelper
end

session2/demo3/app/helpers/say_helper.rb
module SayHelper
end

session2/demo3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

session2/demo3/app/views/myclasses/_form.html.erb
<%= form_for(@myclass) do |f| %>
  <% if @myclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myclass.errors.count, "error") %> prohibited this myclass from being saved:</h2>

      <ul>
      <% @myclass.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

session2/demo3/app/views/myclasses/edit.html.erb
<h1>Editing myclass</h1>

<%= render 'form' %>

<%= link_to 'Show', @myclass %> |
<%= link_to 'Back', myclasses_path %>

session2/demo3/app/views/myclasses/index.html.erb
<h1>Listing myclasses</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @myclasses.each do |myclass| %>
  <tr>
    <td><%= link_to 'Show', myclass %></td>
    <td><%= link_to 'Edit', edit_myclass_path(myclass) %></td>
    <td><%= link_to 'Destroy', myclass, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Myclass', new_myclass_path %>

session2/demo3/app/views/myclasses/new.html.erb
<h1>New myclass</h1>

<%= render 'form' %>

<%= link_to 'Back', myclasses_path %>

session2/demo3/app/views/myclasses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_myclass_path(@myclass) %> |
<%= link_to 'Back', myclasses_path %>

session2/demo3/app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

session2/demo3/app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>hello from <%= @myvar %></p>